In [1]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(uri)
dados.head()

   home  how_it_works  contact  bought
0     1             1        0       0
1     1             1        0       0
2     1             1        0       0
3     1             1        0       0
4     1             1        0       0

In [2]:
x = dados[["home","how_it_works","contact"]]
y = dados[["bought"]]

In [3]:
mapa = { 
    "home" : "principal",
    "how_it_works" : "como_funciona",
    "contact" : "contato",
    "bought" : "comprou"
}
dados = dados.rename(columns = mapa)

In [4]:
x = dados[["principal","como_funciona","contato"]]
y = dados[["comprou"]]

x[:50]

    principal  como_funciona  contato
0           1              1        0
1           1              1        0
2           1              1        0
3           1              1        0
4           1              1        0
5           1              0        1
6           1              1        0
7           1              0        1
8           1              1        0
9           1              0        1
10          1              1        0
11          1              0        1
12          0              0        1
13          0              0        1
14          0              0        1
15          0              0        1
16          0              0        1
17          0              1        0
18          0              0        1
19          0              1        0
20          0              0        1
21          0              1        0
22          0              0        1
23          0              1        0
24          1              0        1
25          1              1        1
26          1              1        1
27          1              0        1
28          0              1        0
29          0              0        1
30          0              1        0
31          1              0        1
32          0              0        1
33          1              0        1
34          1              0        1
35          1              0        1
36          1              0        1
37          0              0        1
38          1              1        0
39          1              0        1
40          0              1        0
41          0              0        1
42          0              1        0
43          1              0        1
44          0              0        1
45          0              0        1
46          1              0        1
47          1              0        1
48          1              1        0
49          1              1        0

In [5]:
y[:50]

    comprou
0         0
1         0
2         0
3         0
4         0
5         1
6         0
7         1
8         0
9         1
10        1
11        1
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        1
25        1
26        1
27        1
28        0
29        0
30        0
31        1
32        0
33        1
34        1
35        1
36        1
37        0
38        0
39        1
40        0
41        0
42        0
43        1
44        0
45        0
46        1
47        1
48        0
49        0

In [6]:
dados.shape

(99, 4)

In [7]:
treino_x = x[:75]
treino_y = y[:75]
teste_x = x[75:]
teste_y = y[75:]

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

Treinaremos com 75 elementos e testaremos com 24 elementos

In [8]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 95.83%

D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

# Usando a biblioteca para separar treino e teste

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%

D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%

D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [11]:
treino_y.value_counts()

comprou
0          47
1          27
Name: count, dtype: int64

In [12]:
teste_y.value_counts()

comprou
0          19
1           6
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y,
                                                         random_state = SEED, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%

D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\guifr\anaconda3\envs\estudo\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [14]:
treino_y.value_counts()

comprou
0          49
1          25
Name: count, dtype: int64

In [15]:
teste_y.value_counts()

comprou
0          17
1           8
Name: count, dtype: int64